### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by domenicoCappello** [domenicoCappello/Byob_client#1]
- [x] Parsing del file di configurazione e creazione lista di oggetti URLDetails
- [x] Implementazione GET e POST HTTP
- [x] Creazione Log file
- [x] Schedulazione delle azioni da intraprendere (Temporizzate) 1 thread per task

**Comment by domenicoCappello** [comment]
- [x] Aggiungere campo maxPeriod al file di configurazione (vedi README.txt su drive)

**Comment by jacklametta** [comment]
Log fatto. La funzione del singleton che scrive è "appoggiata" nel main perchè è stata testata.
.

**Comment by domenicoCappello** [comment]
Alessio
- [x] GUI scrive su conf.txt
- [x] GUI Help Menù
- [x] Id unico bot (Solo per Linux)
- [x] Aggiungere proxy alla GUI

CAPPELLONAH
- [x] Info SO
- [x] browser installati
- [x] Impostazione proxy dalla GUI
- [x] Definizione User Agent e Sleep modes
